# Generated by Django 2.2.12 on 2020-05-10 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminViewConfModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=64)),
                ('selected_columns', models.CharField(max_length=2048, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, null=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_view_conf',
                'unique_together': {('user', 'url_name')},
            },
        ),
    ]
